### ISSUE TITLE
Sender name's case is preserved in local file but not in remote submission

### ISSUE THREAD

**Issue by RoyHP** [hex-agon/chat-logger#11]
As the title says, the local file will preserve the case of the sender's name:
12:50:25 Trism: Are you okay

But remote submission will set the sender name to `trism` - it seems to me like this shouldn't happen, and it should use the case that the client sees.

**Comment by hex-agon** [comment]
Just replying that i'm aware of this and i agree, just can't look into right now. PRs are welcome.
