### ISSUE TITLE
No GIM support

### ISSUE THREAD

**Issue by Starlette7** [hex-agon/chat-logger#13]
Was wanting to utilize this plugin to get my groups levels and rare drops sent to our discord server when they are on mobile.
Kinda doesn't watch the group chat at all.

**Comment by HeyJacob** [comment]
I don't believe it looks at GIM chat whatsoever. I'd love to see this changed.

**Comment by HeyJacob** [comment]
> Was wanting to utilize this plugin to get my groups levels and rare drops sent to our discord server when they are on mobile. Kinda doesn't watch the group chat at all.

I don't believe it looks at GIM chat whatsoever. I'd love to see this changed so that we could get GIM chat logs.

**Comment by sololegends** [comment]
This is resolved, awaiting runelite plugin hub team to merge in the changes. ^.^ 

https://github.com/runelite/plugin-hub/pull/5613
