### ISSUE TITLE
Clan Chat Timestamp Freezes

### ISSUE THREAD

**Issue by greatname100** [hex-agon/chat-logger#2]
I've noticed that the clan chat log will bug out randomly and dozens of messages from different players at different times will all have the same timestamp.
I attached one file as an example of a clan chat log.
Line 193 is where the first instance begins, the second at 286, and so on.
I don't know if this occurs because of me hopping worlds, or possibly even closing Runelite and then opening it up again.
[weird glitch.log](https://github.com/hex-agon/chat-logger/files/5294417/weird.glitch.log)

**Comment by hex-agon** [comment]
I think this might be a side effect of the `Chat history` plugin restoring the messages, i'll have to investigate further

**Comment by greatname100** [comment]
Ok, good point. I'll turn off chat history for now then.
