### ISSUE TITLE
Clan broadcasts no longer being submitted

### ISSUE THREAD

**Issue by KiwiZ0** [hex-agon/chat-logger#23]
Clan broadcast messages like kills, PBs and quest completions are no longer coming through. Regular clan chatter is coming through fine. Seems to have stopped sometime after 12/12 at 11:20pm EST (maybe  on new plugin hub build/release)

Any idea what could be causing this?

**Comment by SaltisRS** [comment]
Seeing the same thing, doesnt trigger an event with my endpoint at all

**Comment by KiwiZ0** [comment]
Might've solved itself around noon EST on Dec 28th

**Comment by hex-agon** [comment]
Fixed internally by RuneLite
