### ISSUE TITLE
Remote Submissions now hanging clients after RuneLite release

### ISSUE THREAD

**Issue by joeysapp** [hex-agon/chat-logger#29]
Hi - I've been running this for a clan to track achievements - since this morning, my code has been hanging users posting in clan chats. I've looked at my own code and it's in line with typical network posts - I had been responding 200/201 and writing back carriage return/newlines until now. Just hangs the user now.

Is there an updated response format expected since yesterday with underlying remote requests for runelite? Thanks!
```
runelite build: RuneLite/1.10.36-a2b6305
```

**Comment by sololegends** [comment]
Thanks for reporting this, I'll look into it today
