### ISSUE TITLE
Feature to copy all game tab output!

### ISSUE THREAD

**Issue by Johno-R** [hex-agon/chat-logger#3]
I am a player owned house host and for a while hosts have been wanting a way to record their donations would it be possible to capture the data in the game tab and send it to a text file?

**Comment by hex-agon** [comment]
If you have the plugin running it is already doing exactly that, any chat message ends up in one of the files, am i misunderstanding something?

**Comment by Johno-R** [comment]
There is a tab called "game" I would like poh donations to be saved to a
file and logged :).

**Comment by hex-agon** [comment]
If i add game message logging i would only add for non-spam messages, does your message get filtered by setting the `game` option to filtered?
