### ISSUE TITLE
Game Chat logging doesn't seem to work

### ISSUE THREAD

**Issue by kittaxi** [hex-agon/chat-logger#31]
Plugin version 1.8.0
Newest Runelite client

![image](https://github.com/user-attachments/assets/c5ba7420-7a4d-4b7b-a7ab-016c2e354c65)

Game chat logging is enabled, but no 'game' folder is created in the chatlogs folder even if new messages are/appear in the "Game" chat section in-game. Public and private logging works perfectly fine. 

Troubleshooting steps done:
- Disabling & reloading the plugin
- Uninstalling & reinstalling the plugin 
- Restarting the client
- Clearing runelite cache

![image](https://github.com/user-attachments/assets/25e218ee-2676-43b3-a018-e769a774dce6)

**Comment by sololegends** [comment]
Thanks for bringing this up! Resolved in v1.8.1 pending Runelite Plugin team acceptance.

https://github.com/runelite/plugin-hub/pull/6545
