### ISSUE TITLE
Optionally hiding image tags

### ISSUE THREAD

**Issue by graftss** [hex-agon/chat-logger#4]
Hi, my friend just found this great plugin and he's been using it to pipe the game chat into a window with a larger font to help his eyes out. 

He was wondering if it would be possible to make it an option in Runelite to not log the \<img> tags. It only really makes sense for his tiny use case, but he'd really appreciate the accommodation if you have the time.

Thanks!

**Comment by hex-agon** [comment]
Hmm i think this falls out a bit of scope for this plugin, i feel this is something your friend should do on his end.
