### ISSUE TITLE
Only logs what I receive

### ISSUE THREAD

**Issue by TerrorNisse** [hex-agon/chat-logger#5]
Is it supposed to only log private messages I receive?  I would really like to see what I send as well. Longer conversations don't make any sense when it's only from the person I talk to :P

Else from that, very nice plugin!

**Comment by hex-agon** [comment]
It should have been fixed on version 1.3.1, is it still happening?

**Comment by TerrorNisse** [comment]
Yes, it works now. I need to start rebooting my client sometimes :P I see another thing though. Could you add "To" and "From"? :)

**Comment by hex-agon** [comment]
If you can, fill another issue with an example of how it is currently and how you would want it to be, i have to consider that it would change for everyone.

Closing this issue as it was solved.
