### ISSUE TITLE
Add To/from in a private message

### ISSUE THREAD

**Issue by TerrorNisse** [hex-agon/chat-logger#6]
Right now the log looks like this:

_23:04:53 SomeUser: Hey man! You good? :)
23:05:43 SomeUser: I'm great, you?_

Would love to see it like this:

_23:04:53 From SomeUser: Hey man! You good? :)
23:05:43 To SomeUser: I'm great, you?_

Great work on the plugin. It's very useful.

-Joacim

**Comment by hex-agon** [comment]
Seems like a reasonable request, i'll take a whilethough as i want to sit down and do a bigger-ish update including clan and guest chats.

**Comment by TerrorNisse** [comment]
Very understandable :) Thanks!

**Comment by hex-agon** [comment]
Added in d80badcbe2e6b5d7e187a2524a3ea94c475a23ae
