### ISSUE TITLE
Add support for new clan chat system

### ISSUE THREAD

**Issue by theshapersarecoming** [hex-agon/chat-logger#7]
Since the new clan system released this plugin is no longer useful for saving clan chat logs. Can we please have support for the new type as well?

https://oldschool.runescape.wiki/w/Clan

**Comment by hex-agon** [comment]
On the plans, haven't sat down to work on it yet

**Comment by MathieuDR** [comment]
I see that you updated for the clan chat support, is this done?
Or is there extra work to be done?

**Comment by theshapersarecoming** [comment]
@hex-agon Having remote support for the clan chat would be ideal.

**Comment by hex-agon** [comment]
Remote support still requires further investigation, this *should* work for logging locally but i haven't tested it. I'm in the middle of switching jobs and it has been taking a toll on me.

**Comment by hex-agon** [comment]
Added in de67eef17ec4d31b23185fa7e985e9ea1d946015 and c385050f912066cb41a2049f4e7c9bff8a2efe71

**Comment by hex-agon** [comment]
@theshapersarecoming pay attention to changes in the remote submission payloads, they're documented in the README
