### ISSUE TITLE
Support for Join/Leave Notifications

### ISSUE THREAD

**Issue by Anonagonn** [hex-agon/chat-logger#8]
This plugin has been working very well for me so far, but I've noticed one thing missing that I would like to see implemented. In RuneLite's "Chat Channels" plugin, there is an option to display join/leave messages that notify you whenever a user joins or leaves the channel, and from what I've seen these messages aren't picked up by the chat logger. Would support for these messages be possible to implement?

**Comment by hex-agon** [comment]
The functionality you've described is implemented by a RuneLite plugin meaning they don't have their own message type. Since these messages are not real I don't really want them to be logged in the plugin.
