### ISSUE TITLE
Allow people to set the amount of days logs are stored

### ISSUE THREAD

**Issue by Im2be** [hex-agon/chat-logger#9]
Currently, logs are being saved for 30 days max. I'd like to keep my logs permanently. Would it be possible to have a config setting like "Keep logs for X days:" with a slider or input field?

Possible syntax: 

- n <= 0: keep logs indefinitely
- n > 0: keep logs for n days

**Comment by that-mint** [comment]
+1, what is even the point of this? lots of people have a lot of storage.

**Comment by Ckrisirkc** [comment]
Another +1.  
This seems drastically less useful with it only storing the past 30 days, and I didn't even realize until I tried to search some old logs only to discover they're gone.

**Comment by sololegends** [comment]
This is resolved, awaiting runelite plugin hub team to merge in the changes. ^.^ 

https://github.com/runelite/plugin-hub/pull/5613
